//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_PLCStatus
    {
        public Nullable<int> LineID { get; set; }
        public string StationNo { get; set; }
        public Nullable<int> AndonCall { get; set; }
        public Nullable<int> ReadStatus { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
