//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_LINESTATUS_BODYSHOP
    {
        public decimal LINEID { get; set; }
        public string STATIONNO { get; set; }
        public decimal BUILDNO { get; set; }
        public Nullable<System.DateTime> ENGINEMOVEDATE { get; set; }
        public Nullable<decimal> IPCSTATUS { get; set; }
        public Nullable<decimal> ANDONCALL { get; set; }
        public Nullable<int> READSTATUS { get; set; }
        public Nullable<decimal> PLATTENID { get; set; }
        public Nullable<decimal> TAKTTIMESECONDS { get; set; }
    }
}
