//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_ANDON_Stations
    {
        public decimal LINEID { get; set; }
        public string STATIONNO { get; set; }
        public decimal TIMESECONDS { get; set; }
        public System.DateTime LASTUPDATED { get; set; }
        public Nullable<int> READSTATUS { get; set; }
        public Nullable<int> LINESTATUS { get; set; }
    }
}
