//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Andon_IndexLog
    {
        public decimal Keyx { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public decimal LineID { get; set; }
        public string StationNO { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
    }
}
