//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_Andon
    {
        public decimal LineID { get; set; }
        public decimal TimeSeconds { get; set; }
        public decimal LineStatus { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<decimal> ReadStatus { get; set; }
    }
}
