//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AML_LineStatus
    {
        public decimal LineID { get; set; }
        public string StationNO { get; set; }
        public string BuildNo { get; set; }
        public Nullable<System.DateTime> EngineMoveDate { get; set; }
        public Nullable<decimal> IPCStatus { get; set; }
        public Nullable<decimal> AndonCALL { get; set; }
        public Nullable<int> ReadStatus { get; set; }
    }
}
