//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AML_PROD_20180726Entities : DbContext
    {
        public AML_PROD_20180726Entities()
            : base("name=AML_PROD_20180726Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AML_Andon> AML_Andon { get; set; }
        public virtual DbSet<AML_Andon_IndexLog> AML_Andon_IndexLog { get; set; }
        public virtual DbSet<AML_ANDON_Stations> AML_ANDON_Stations { get; set; }
        public virtual DbSet<AML_LineStatus> AML_LineStatus { get; set; }
        public virtual DbSet<AML_PLC_BuildList> AML_PLC_BuildList { get; set; }
        public virtual DbSet<AML_PLCStatus> AML_PLCStatus { get; set; }
        public virtual DbSet<AML_LINESTATUS_BODYSHOP> AML_LINESTATUS_BODYSHOP { get; set; }
        public virtual DbSet<AML_PLC_BuildList_LOG> AML_PLC_BuildList_LOG { get; set; }
        public virtual DbSet<LINE> LINES { get; set; }
        public virtual DbSet<STATION> STATIONS { get; set; }
    }
}
