//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE
    {
        public decimal LINEID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PlantID { get; set; }
        public string LINECODE { get; set; }
    }
}
