//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLLinesEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATION
    {
        public decimal LINEID { get; set; }
        public string ABSNNO { get; set; }
        public string ABSNDESC { get; set; }
        public string ABSNSTART { get; set; }
        public string ABSNEND { get; set; }
        public Nullable<decimal> Operators { get; set; }
        public Nullable<decimal> OSMREQUIRED { get; set; }
        public Nullable<bool> PARTPROCESS { get; set; }
        public Nullable<bool> DOCVIEWFIRST { get; set; }
    }
}
