// <auto-generated />
namespace PrismApp1.Persistence.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialdB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialdB));
        
        string IMigrationMetadata.Id
        {
            get { return "202009130457549_InitialdB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
